spring.application.name=Game-Library

spring.datasource.url=jdbc:postgresql://localhost:5432/game_library
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver